version: "3"

services:

 web:
  build:
    context: .
    dockerfile: Dockerfile.dev
  ports:
     - "8080:3000"
  volumes:
      - /home/app/node_modules
      - .:/home/app/

 test-app:
  build:
    context: .
    dockerfile: Dockerfile.dev
  volumes:
      - /home/app/node_modules
      - .:/home/app/
  command: ["npm","run","test"]

